services:
  serena:
    image: serena:latest
    # To work with projects, you must mount them as volumes:
    volumes:
      - ./serena_projects/pymodaq_plugins_urashg:/workspace/pymodaq_plugins_urashg
      # - /path/to/another/project:/workspace/another-project
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERENA_PORT:-9121}:9121" # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282" # Dashboard port (default 0x5EDA = 24282)
    environment:
      - SERENA_DOCKER=1
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        source .venv/bin/activate
        exec uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0

  serena-dev:
    image: serena:dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    environment:
      - SERENA_DOCKER=1
    volumes:
      - .:/workspaces/serena
    ports:
      - "${SERENA_DEV_PORT:-9122}:9121" # MCP server port
      - "${SERENA_DEV_DASHBOARD_PORT:-24283}:24282" # Dashboard port
    command:
      - "uv run --directory . serena-mcp-server"
