[plugin-info]
name = "pymodaq_plugins_urashg"
version = "0.1.0"
description = "PyMoDAQ plugin package for URASHG (Ultrafast Reflection-mode Angle-resolved Second Harmonic Generation) microscopy systems"
author = "PyMoDAQ Plugin Development Team"
author-email = "contact@pymodaq.org"
homepage = "https://github.com/PyMoDAQ/pymodaq_plugins_urashg"
package-url = "https://github.com/PyMoDAQ/pymodaq_plugins_urashg"
bugtrack-url = "https://github.com/PyMoDAQ/pymodaq_plugins_urashg/issues"

[plugin-info.classifiers]
development-status = "Alpha"
environment = "X11"
intended-audience = ["Science/Research", "Developers"]
license = "MIT"
operating-system = ["Microsoft :: Windows", "POSIX :: Linux"]
programming-language = "Python :: 3"
topic = [
    "Scientific/Engineering :: Physics",
    "Scientific/Engineering :: Visualization",
]

[plugin-info.entry-points]

[plugin-info.entry-points.move_plugins]
RedPitayaFPGA = "pymodaq_plugins_urashg.daq_move_plugins.daq_move_redpitaya_fpga:DAQ_Move_RedPitayaFPGA"
Elliptec = "pymodaq_plugins_urashg.daq_move_plugins.daq_move_elliptec:DAQ_Move_Elliptec"
MaiTaiLaser = "pymodaq_plugins_urashg.daq_move_plugins.daq_move_maitai_laser:DAQ_Move_MaiTaiLaser"

[plugin-info.entry-points.viewer_plugins]
PyVCAM = "pymodaq_plugins_urashg.daq_viewer_plugins.plugins_2D.daq_2dviewer_pyvcam:DAQ_2DViewer_PyVCAM"

[plugin-info.entry-points.h5exporters]
# Future: Custom HDF5 exporters for RASHG data

[plugin-info.entry-points.extensions]
# Future: Custom PyMoDAQ extensions for RASHG workflows

[plugin-info.entry-points.pid_models]
# Future: Custom PID models for laser stabilization

[hardware-compatibility]
manufacturers = ["Thorlabs", "Photometrics", "Red Pitaya", "Spectra-Physics"]

[hardware-compatibility.actuators]
"Thorlabs ELL14" = {
    plugin = "Elliptec",
communication = "Serial/USB",
description = "Motorized rotation mount for polarization control",

}

"Red Pitaya PID" = {
    plugin = "RedPitayaFPGA",
communication = "Ethernet/Memory-mapped",
description = "FPGA-based PID controller for laser stabilization",

}

"MaiTai Laser" = {
    plugin = "MaiTaiLaser",
communication = "Serial/Ethernet",
description = "Ultrafast laser with EOM power control",

}

tested_models = ["ELL14", "ELL14K"]
tested_models = ["STEMlab 125-14", "STEMlab 125-10"]
tested_models = ["MaiTai eHP", "MaiTai HP"]
[hardware-compatibility.detectors]
"Photometrics Prime BSI" = {
    plugin = "PyVCAM",
communication = "USB 3.0/PCIe",
description = "Scientific CMOS camera for SHG detection",

}

tested_models = ["Prime BSI", "Prime BSI Express"]
[software-dependencies]
pymodaq = ">=4.0.0"
numpy = ">=1.20.0"
pyqt5 = ">=5.15.0"
pyqtgraph = ">=0.12.0"
h5py = ">=3.0.0"
scipy = ">=1.7.0"
matplotlib = ">=3.3.0"

[software-dependencies.hardware-specific]
pyvcam = { version = ">=1.0.0", description = "Photometrics camera control" }
elliptec = { version = ">=0.1.0", description = "Thorlabs ELL14 rotation mount control" }

[software-dependencies.optional]
opencv-python = { version = ">=4.5.0", description = "Advanced image processing" }
scikit-image = { version = ">=0.18.0", description = "Image analysis tools" }
pymodaq-plugins-mock = { version = ">=1.0.0", description = "Mock devices for testing" }
pymodaq-plugins-daqmx = { version = ">=1.0.0", description = "Future galvo mirror integration" }

[documentation]
user-guide = "https://pymodaq-plugins-urashg.readthedocs.io/en/latest/user_guide.html"
api-reference = "https://pymodaq-plugins-urashg.readthedocs.io/en/latest/api.html"
hardware-setup = "https://pymodaq-plugins-urashg.readthedocs.io/en/latest/hardware_setup.html"
examples = "https://github.com/PyMoDAQ/pymodaq_plugins_urashg/tree/main/examples"
troubleshooting = "https://pymodaq-plugins-urashg.readthedocs.io/en/latest/troubleshooting.html"
