[plugin-info]
name = "pymodaq_plugins_urashg"
description = "PyMoDAQ plugin package for URASHG microscopy systems"
author = "TheFermiSea"
author-email = "squires.b@gmail.com"
homepage = "https://github.com/TheFermiSea/pymodaq_plugins_urashg"

[hardware-compatibility]
manufacturers = ["Thorlabs", "Photometrics", "Newport"]

[hardware-compatibility.actuators]
"Thorlabs ELL14" = { plugin = "DAQ_Move_Elliptec", communication = "Serial" }
"Newport ESP300" = { plugin = "DAQ_Move_ESP300", communication = "Serial" }
"MaiTai Laser" = { plugin = "DAQ_Move_MaiTai", communication = "Serial" }

[hardware-compatibility.detectors]
"Photometrics Prime BSI" = { plugin = "DAQ_2DViewer_PrimeBSI", communication = "USB 3.0" }
"Newport 1830-C" = { plugin = "DAQ_0DViewer_Newport1830C", communication = "Serial" }
