# Configuration template for PyMoDAQ URASHG Plugin Package

[urashg]
# Main configuration section for URASHG microscopy

[urashg.hardware]
# Hardware connection defaults

[urashg.hardware.elliptec]
# Elliptec rotation mounts configuration
serial_port = "/dev/ttyUSB0"
baudrate = 9600
timeout = 2.0

[urashg.hardware.camera]
# Photometrics Prime BSI camera configuration
exposure_time = 100       # milliseconds
gain = 1
cooling_temperature = -20 # Celsius

[urashg.hardware.maitai]
# MaiTai laser configuration
serial_port = "/dev/ttyUSB1"
baudrate = 9600
timeout = 5.0

[urashg.hardware.newport]
# Newport 1830-C power meter configuration
gpib_address = 1
timeout = 5.0
wavelength = 800.0 # nm

[urashg.measurement]
# Default measurement parameters
averaging_frames = 3
laser_power = 100.0   # milliwatts
exposure_time = 100.0 # milliseconds
