# PyMoDAQ URASHG Plugin Configuration File
# This file contains default configuration settings for the URASHG plugin package

[metadata]
config_version = "1.0.0"
plugin_name = "pymodaq_plugins_urashg"
description = "Configuration for μRASHG microscopy system plugins"

[presets]
# Default preset configuration for the extension
preset_for_urashgmicroscopyextension = "urashg_microscopy_system"
default_preset = "urashg_microscopy_system"
auto_load_preset = true

[hardware]
# Hardware device default configurations

[hardware.elliptec]
default_port = "/dev/ttyUSB1"
baudrate = 9600
timeout = 2.0
mount_addresses = "2,3,8"
home_on_connect = false
position_tolerance = 0.1      # degrees

[hardware.maitai]
default_port = "/dev/ttyUSB0"
baudrate = 115200
timeout = 2.0
wavelength_min = 700
wavelength_max = 900
stabilization_time = 2.0      # seconds

[hardware.primebsi]
default_camera = "pvcamUSB_0"
default_exposure = 10.0       # ms
cooling_enabled = true
target_temperature = -20.0    # °C

[hardware.primebsi.default_roi]
x = 0
y = 0
width = 2048
height = 2048

[hardware.newport1830c]
default_port = "/dev/ttyS0"
baudrate = 9600
timeout = 2.0
default_wavelength = 780.0  # nm
default_units = "W"
averaging_count = 3

[hardware.esp300]
default_host = "192.168.1.100"
default_port = 5001
timeout = 5.0
axis_count = 1
position_tolerance = 0.01      # mm

[measurement]
# Default measurement configuration
default_type = "Basic RASHG"
polarization_steps = 36
integration_time = 100.0     # ms
stabilization_time = 0.5     # seconds

[measurement.safety]
max_laser_power = 50.0  # %
movement_timeout = 10.0 # seconds
camera_timeout = 5.0    # seconds

[data]
# Data management configuration
auto_save = true
save_format = "HDF5"
save_raw_images = false
default_path = "~/rashg_data"
file_prefix = "urashg_measurement"

[analysis]
# Analysis configuration
auto_fit = true
fit_function = "I = A + B*cos(4θ + φ)"
r_squared_threshold = 0.9
contrast_threshold = 0.1

[ui]
# User interface configuration
update_interval = 5.0      # seconds
plot_update_rate = 2.0     # Hz
status_display_lines = 100
theme = "default"

[paths]
# Default paths for various plugin components
preset_directory = "presets"
data_directory = "data"
config_directory = "config"
log_directory = "logs"

[logging]
# Logging configuration
level = "INFO"
file_logging = true
console_logging = true
max_log_files = 10
max_log_size_mb = 10

[testing]
# Testing configuration
mock_mode_default = false
hardware_test_timeout = 30.0     # seconds
integration_test_enabled = true
performance_test_enabled = false
